
<!doctype html>
<html lang="cs">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>
            
                Beginners course PyLadies Vienna: Exceptions
            
        </title>

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

        
        <link rel="icon" type="image/x-icon" href= "/static/img/who_96px.png">
        <link rel="stylesheet" href="/static/css/naucse.css">
        <link rel="stylesheet" href="/static/css/body.css">
        <link rel="stylesheet" href="/static/css/pygments-lovelace-style.css">
        <link rel="stylesheet" href="/static/css/ipython.css">

        
    <link rel="canonical" href="https://naucse.python.cz/lessons/beginners-en/exceptions/" />


        <style>
            
    

        </style>
    </head>

    <body>
        <nav class="header">
            <ul class="container menu">
                <li><a href="/" class="logo"><h1>PyLadies Vienna</h1></a></li>
                <li><a href="/sponsorship/" class="menu-link"><h2>Support Us</h2></a></li>
                <li><a href="/mentorship/" class="menu-link"><h2>Mentorship</h2></a></li>
                <li><a href="/runs/" class="menu-link"><h2>Courses</h2></a></li>
            </ul>
        </nav>

        

<div class="page">
    <div class="container">

        
  


        <div class="lesson-content">
          
    

    <h1>Exceptions</h1>
<p>We have already talked about <a href="/2021/pyladies-en-vienna-2021/beginners-en/print/">error messages</a>.
When an error occurs, Python complains, tells us where the error (line) is,
and terminates the program.  But there is much more that we can learn about
error messages (aka <em>exceptions</em>).</p>
<h2>Printing errors:</h2>
<p>Let's repeat how Python prints an error which is in a nested function.</p>
<div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">outer_function</span><span class="p">():</span>
    <span class="k">return</span> <span class="n">inner_function</span><span class="p">(</span><span class="mi">0</span><span class="p">)</span>

<span class="k">def</span> <span class="nf">inner_function</span><span class="p">(</span><span class="n">divisor</span><span class="p">):</span>
    <span class="k">return</span> <span class="mi">1</span> <span class="o">/</span> <span class="n">divisor</span>

<span class="nb">print</span><span class="p">(</span><span class="n">outer_function</span><span class="p">())</span>
</pre></div><p>When we run the code it stops with an error and a message like:</p>
<p><!-- XXX: Highlight the line numbers --></p>
<div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">"example.py"</span>, line <span class="m">7</span>, in <span class="n">&lt;module&gt;</span>
<span class="w">    </span><span class="nb">print</span><span class="p">(</span><span class="n">outer_function</span><span class="p">())</span>
  File <span class="nb">"example.py"</span>, line <span class="m">2</span>, in <span class="n">outer_function</span>
<span class="w">    </span><span class="k">return</span> <span class="n">inner_function</span><span class="p">(</span><span class="mi">0</span><span class="p">)</span>
  File <span class="nb">"example.py"</span>, line <span class="m">5</span>, in <span class="n">inner_function</span>
<span class="w">    </span><span class="k">return</span> <span class="mi">1</span> <span class="o">/</span> <span class="n">divisor</span>
<span class="gr">ZeroDivisionError</span>: <span class="n">division by zero</span>
</pre></div><p>Python can't know where the original error is that needs to be fixed, so it shows
you everything in the error message.</p>
<p>Either we shouldn't call <code>in_func</code> with argument <code>0</code>.</p>
<p>Or the <code>in_function</code> must be written to handle the case that the divisor can be <code>0</code>
and it should do something else than try to divide by zero.</p>
<h2>Raising an exception</h2>
<p>In Python, an <em>exception</em> is raised by the command <code>raise</code>.
The command is followed by the name of the exception we want to raise and
an optional short description of what went wrong (in parentheses).</p>
<div class="highlight"><pre><span></span><span class="n">MAX_ALLOWED_VALUE</span> <span class="o">=</span> <span class="mi">20</span>

<span class="k">def</span> <span class="nf">verify_number</span><span class="p">(</span><span class="n">number</span><span class="p">):</span>
    <span class="k">if</span> <span class="n">number</span> <span class="o">&lt;</span> <span class="mi">0</span> <span class="ow">or</span> <span class="n">number</span> <span class="o">&gt;=</span> <span class="n">MAX_ALLOWED_VALUE</span><span class="p">:</span>
        <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span><span class="sa">f</span><span class="s2">"The number </span><span class="si">{</span><span class="n">number</span><span class="si">}</span><span class="s2"> is not in the allowed range!"</span><span class="p">)</span>
    <span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s2">"The number </span><span class="si">{</span><span class="n">number</span><span class="si">}</span><span class="s2"> is OK!"</span><span class="p">)</span>

<span class="n">verify_number</span><span class="p">(</span><span class="mi">5</span><span class="p">)</span>
<span class="n">verify_number</span><span class="p">(</span><span class="mi">25</span><span class="p">)</span>
</pre></div><p>What exceptions are available in Python?
Python provides a hierarchy of standard (built-in) exceptions. This
is just a subset of them:</p>
<div class="highlight"><pre><code>BaseException
 ├── SystemExit                     raised by function exit()
 ├── KeyboardInterrupt              raised after pressing Ctrl+C
 ╰── Exception
      ├── ArithmeticError
      │    ╰── ZeroDivisionError    zero division
      ├── AssertionError            command `assert` failed
      ├── AttributeError            non-existing attribute, e.g. 'abc'.len
      ├── ImportError               failed import
      ├── LookupError
      │    ├── IndexError           non-existing index, e.g. 'abc'[999]
      │    ╰── KeyError             non-existing dictionary key
      ├── NameError                 used a non-existing variable name
      │    ╰── UnboundLocalError    used a variable that wasn't initiated
      ├── OSError
      │    ╰── FileNotFoundError    requested file does not exist
      ├── SyntaxError               wrong syntax – program is unreadable/unusable
      │    ╰── IndentationError     wrong indentation
      │         ╰── TabError        combination of tabs and spaces
      ├── TypeError                 wrong type, e.g. "a" + 1
      ╰── ValueError                wrong value, e.g. int('xyz')</code></pre></div><div class="admonition note"><p class="admonition-title">What does this hierarchy mean?</p>
<p>The hierarchy of exceptions is like a family tree with the most generic type
of exception as the root, every branch becoming more specific.
E.g., <code>KeyError</code> is also a <code>LookupError</code> and <code>Exception</code> but it is
not, e.g., a <code>SyntaxError</code>.</p>
<p>You will learn more about these hierarchies and when we will talk about
the Object Oriented Programming, classes and inheritance.</p>
<p>For the moment, it is enough to say that the exceptions are <strong>classes</strong> and
that the more specific <strong>child</strong> exceptions <strong>inherit</strong> the properties
of their generic generic <strong>parent</strong>.  Namely, the <code>Exception</code> is the parent
class of the <code>LookupError</code> and the <code>LookupError</code> is the parent classes of the
<code>KeyError</code> exception. Therefore the <code>KeyError</code> has properties
of <code>LookupError</code> and <code>Exception</code> exceptions.</p>
</div><p>For the full list of built-in exception see the <a href="https://docs.python.org/3/library/exceptions.html">Python documentation</a>.</p>
<h2>Handling Exceptions</h2>
<p>Why there are so many built-in exceptions? Because this way we can more easily
<em>catch</em> exceptions of specific error states.</p>
<p>It is not always desired that an exception kills our program. And we also cannot
(or do not want to) cover all possible error conditions in the code
where the exceptions are raised from.</p>
<p>Let me show you an example:</p>
<div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">prompt_number</span><span class="p">():</span>
    <span class="n">answer</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s1">'Enter some number: '</span><span class="p">)</span>
    <span class="k">if</span> <span class="ow">not</span> <span class="n">answer</span><span class="p">:</span>
        <span class="k">return</span> <span class="kc">None</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">number</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="n">answer</span><span class="p">)</span>
    <span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
        <span class="nb">print</span><span class="p">(</span><span class="s1">'That is not a number! I will continue with 0'</span><span class="p">)</span>
        <span class="n">number</span> <span class="o">=</span> <span class="mi">0</span>
    <span class="k">return</span> <span class="n">number</span>

<span class="nb">print</span><span class="p">(</span><span class="s2">"Press ENTER to stop the script."</span><span class="p">)</span>
<span class="k">while</span> <span class="kc">True</span><span class="p">:</span>
    <span class="n">number</span> <span class="o">=</span> <span class="n">prompt_number</span><span class="p">()</span>
    <span class="k">if</span> <span class="n">number</span> <span class="ow">is</span> <span class="kc">None</span><span class="p">:</span>
        <span class="k">break</span>
    <span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s2">"Entered number: </span><span class="si">{</span><span class="n">number</span><span class="si">}</span><span class="s2">"</span><span class="p">)</span>
</pre></div><p>Run the code and try different inputs. What happens if the input is not
an integer number?</p>
<p>Invalid input does not cause an error, instead it gets replaced by <code>0</code>.</p>
<p>So how does this work?</p>
<p>We call the <code>int()</code> function within the <code>try</code> block.
If there is no error, this function is executed, it returns a value which
is assigned to the <code>number</code> variable and leaves the <code>try</code> block.</p>
<p>In case of a <code>ValueError</code> exception raised by <code>int()</code> caused by an invalid input
value, this exception is caught and the execution continues
in the <code>except ValueError</code> block. There, a message is printed and
<code>0</code> is assigned to the <code>number</code> variable.</p>
<p>In this case we specifically catch the <code>ValueError</code> exception.
We could achieve the same by catching generic <code>Exception</code>, because, as you can
see in the hierarchy above, <code>ValueError</code> is a specific type of <code>Exception</code>.</p>
<h2>Don't catch'em all!</h2>
<p>Try to be as selective as possible when catching the expected exceptions.
There is no need to catch the most of the errors.</p>
<div class="admonition note"><p>When an unexpected error happens it is <strong>much better</strong> to terminate the program
rather than to continue with wrong values.
When an unexpected error happens we want to know about it as soon as it
appears. With the wrong values bad things will happen later in the code anyway
and the real cause will be <strong>difficult</strong> to trace.</p>
</div><p>For example, catching the exception <code>KeyboardInterrupt</code>
could have the side effect that the program couldn't be terminated if we needed to
(with shortcut <kbd>Ctrl</kbd>+<kbd>C</kbd>).</p>
<p>Use the command <code>try/except</code> only in situations when you
anticipate some exception, i.e., you know exactly what can happen
and why, and you are able to fix the error state in the except block.</p>
<p>A typical example would be reading the input from a user. If the user
enters gibberish, it is better to ask again until the
user enters something meaningful:</p>
<div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">def</span> <span class="nf">fetch_number</span><span class="p">():</span>
<span class="gp">... </span>    <span class="k">while</span> <span class="kc">True</span><span class="p">:</span>
<span class="gp">... </span>        <span class="n">answer</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s2">"Type a number: "</span><span class="p">)</span>
<span class="gp">... </span>        <span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>            <span class="k">return</span> <span class="nb">int</span><span class="p">(</span><span class="n">answer</span><span class="p">)</span>
<span class="gp">... </span>        <span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
<span class="gp">... </span>            <span class="nb">print</span><span class="p">(</span><span class="s2">"Oi! This is rubbish, mate! Do it again!"</span><span class="p">)</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">fetch_number</span><span class="p">()</span>
<span class="go">Type a number: nan</span>
<span class="go">Oi! This is trash, mate! Do it again!</span>
<span class="go">Type a number: 42</span>
<span class="go">42</span>
</pre></div><h2>Other clauses</h2>
<p>Additionally to <code>except</code>, there are two more clauses - blocks that can 
be used with <code>try</code>, and these are <code>else</code> and <code>finally</code>.</p>
<p>The first one <code>else</code> will be run if no exception in the <code>try</code> block was raised.
And <code>finally</code> runs every time and is executed even in the case of an uncaught exception
and may be used even without any <code>except</code> clause. It is mostly used for clean-ups.</p>
<p>You can also have several <code>except</code> blocks. Only one of them will be triggered. 
The first one that can handle the raised exception.</p>
<div class="admonition note"><p>Always catch more specific exceptions before the generic ones.</p>
</div><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="n">do_something</span><span class="p">()</span>
<span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">"This will be printed if there's a ValueError."</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">NameError</span><span class="p">,</span> <span class="ne">KeyError</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">"This will be printed if there's a NameError or KeyError."</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">"This will be printed if there's some other exception."</span><span class="p">)</span>
    <span class="nb">print</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>
    <span class="c1"># (apart from SystemExit a KeyboardInterrupt, we don't want to catch those)</span>
<span class="k">except</span> <span class="ne">TypeError</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">"This will never be printed"</span><span class="p">)</span>
    <span class="c1"># ("except Exception" above already caught the TypeError)</span>
<span class="k">else</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">"This will be printed if there's no error in try block"</span><span class="p">)</span>
<span class="k">finally</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">"This will always be printed; even if there's e.g. a 'return' in the 'try' block."</span><span class="p">)</span>
</pre></div><h2>Task</h2>
<p>Let's add exception handling and proper input checking to our square size
calculator from <a href="/2021/pyladies-en-vienna-2021/beginners-en/comparisons/">comparisons lesson</a>.</p>
<p>Modify the code so that until the user enters a non-negative
number the programs will keep prompting for the input again.</p>
<div class="solution" id="solution-0">
    <h3>Solution</h3>
    <div class="solution-cover">
        <a href="/2021/pyladies-en-vienna-2021/beginners-en/exceptions/index/solutions/0/"><span class="link-text">Show solution</span></a>
    </div>
    <div class="solution-body" aria-hidden="true">
        <div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">input_side</span><span class="p">():</span>
    <span class="k">while</span> <span class="kc">True</span><span class="p">:</span>
        <span class="n">raw_input</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s2">"Enter the side of a square in centimeters: "</span><span class="p">)</span>
        <span class="k">try</span><span class="p">:</span>
            <span class="n">side</span> <span class="o">=</span> <span class="nb">float</span><span class="p">(</span><span class="n">raw_input</span><span class="p">)</span>
        <span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
            <span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s2">"</span><span class="si">{</span><span class="n">raw_input</span><span class="si">}</span><span class="s2"> is not a number!"</span><span class="p">)</span>
        <span class="k">else</span><span class="p">:</span>
            <span class="k">if</span> <span class="n">side</span> <span class="o">&lt;=</span> <span class="mi">0</span><span class="p">:</span>
                <span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s2">"</span><span class="si">{</span><span class="n">raw_input</span><span class="si">}</span><span class="s2"> is a negative number!"</span><span class="p">)</span>
            <span class="k">else</span><span class="p">:</span>
                <span class="k">break</span>
    <span class="k">return</span> <span class="n">side</span>
<span class="n">side</span> <span class="o">=</span> <span class="n">input_side</span><span class="p">()</span>
<span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s2">"The perimeter of a square with a side of </span><span class="si">{</span><span class="n">side</span><span class="si">}</span><span class="s2"> cm is </span><span class="si">{</span><span class="n">side</span><span class="w"> </span><span class="o">*</span><span class="w"> </span><span class="mi">4</span><span class="si">}</span><span class="s2"> cm."</span><span class="p">)</span>
<span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s2">"The area of a square with a side of </span><span class="si">{</span><span class="n">side</span><span class="si">}</span><span class="s2"> cm is </span><span class="si">{</span><span class="n">side</span><span class="w"> </span><span class="o">**</span><span class="w"> </span><span class="mi">2</span><span class="si">}</span><span class="s2"> cm2."</span><span class="p">)</span>
</pre></div>
    </div>
</div>


        </div>

        


        
    <div class="row prev-next">
        
            
            
                
    <div class="col text-left">
        <a href="/2021/pyladies-en-vienna-2021/sessions/testing/">↑ <span class="d-none d-sm-inline">Lesson: Testing</span></a>
    </div>

            
            
                
    <div class="col text-right">
        <a href="/2021/pyladies-en-vienna-2021/beginners-en/modules/"><span class="d-none d-sm-inline">Modules</span> →</a>
    </div>

            
        
    </div>


        

    </div>
</div>



        <script type="text/javascript" src="/static/js/solutions.js"></script>

        <div class="footer container">
            <hr>
            <div class="lesson-attribution">
                
    
        <p>Translated by Marketa Muzikova</p>
    
        <p>Originally written by Petr Viktorin, 2014-2017 for <a href="https://naucse.python.cz/course/pyladies/beginners/exceptions/">PyLadies CZ</a>.</p>
    

                
    <p>
        Licence:
        <a href="https://creativecommons.org/licenses/by-sa/4.0/">
            Creative Commons Attribution-ShareAlike 4.0 International
        </a>
    </p>
    

                
            </div>
        </div>
        <footer>
            <div class="container">
                <div class="global-pyladies">
                  © 2024 PyLadies Vienna. All rights reserved.
                  <br>
                  <a href="/agb/">Impressum, AGB</a>
                  <br>
                  We are a part of <a href="https://pyladies.com">international PyLadies</a>.
                </div>
                <ul>
                    <li>
                        <a href="https://discord.gg/v2qdvbD2dn" target="_blank">
                            <img src="/static/img/discord-logo.png">
                        </a>
                    </li>
                    <li>
                        <a href="mailto:pyladies.vienna@gmail.com" >
                            <img src="/static/img/mail-white.png">
                        </a>
                    </li>
                    <li>
                        <a href="https://twitter.com/pyladies_vie" target="_blank">
                            <img src="/static/img/twitter-white.png">
                        </a>
                    </li>
                    <li>
                        <a href="https://www.instagram.com/pyladies_vienna" target="_blank">
                            <img src="/static/img/instagram-logo.png">
                        </a>
                    </li>
                    <li>
                        <a href="https://github.com/UndeadFairy/pyladies_vienna" target="_blank">
                            <img src="/static/img/github-white.png">
                        </a>
                    </li>
                    <li>
                        <a href="https://www.meetup.com/PyLadies-Vienna/" target="_blank">
                            <img src="/static/img/meetup.png">
                        </a>
                    </li>
                    <li data-toggle="tooltip" title="Linkedin">
                      <a href="https://www.linkedin.com/company/pyladies-vienna" target="_blank">
                          <img src="/static/img/linkedin-logo.png">
                      </a>
                    </li>
                </ul>
            </div>
            <div class="clear"></div>
          </footer>

        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

        

    </body>
</html>